import type { Ability, EggGroup, Type } from '../entities'

export const translateType = (rawName: Type) => {
  switch (rawName) {
    case 'normal':
      return 'ノーマル'
    case 'fire':
      return 'ほのお'
    case 'water':
      return 'みず'
    case 'grass':
      return 'くさ'
    case 'electric':
      return 'でんき'
    case 'ice':
      return 'こおり'
    case 'fighting':
      return 'かくとう'
    case 'poison':
      return 'どく'
    case 'ground':
      return 'じめん'
    case 'flying':
      return 'ひこう'
    case 'psychic':
      return 'エスパー'
    case 'bug':
      return 'むし'
    case 'rock':
      return 'いわ'
    case 'ghost':
      return 'ゴースト'
    case 'dragon':
      return 'ドラゴン'
    case 'dark':
      return 'あく'
    case 'steel':
      return 'はがね'
    case 'fairy':
      return 'フェアリー'
    default:
      return 'ふめい'
  }
}

export const translateEggGroup = (rawName: EggGroup) => {
  switch (rawName) {
    case 'monster':
      return 'かいじゅう'
    case 'water1':
      return 'すいちゅう1'
    case 'bug':
      return 'むし'
    case 'flying':
      return 'ひこう'
    case 'ground':
      return 'りくじょう'
    case 'fairy':
      return 'ようせい'
    case 'plant':
      return 'しょくぶつ'
    case 'humanshape':
      return 'ひとがた'
    case 'water3':
      return 'すいちゅう3'
    case 'mineral':
      return 'こうぶつ'
    case 'indeterminate':
      return 'ふていけい'
    case 'water2':
      return 'すいちゅう2'
    case 'ditto':
      return 'メタモン'
    case 'dragon':
      return 'ドラゴン'
    case 'no-eggs':
      return 'タマゴみはっけん'
    default:
      return 'ふめい'
  }
}

export const translateAbility = (rawName: Ability['name']) => {
  switch (rawName) {
    case 'stench':
      return 'あくしゅう'
    case 'drizzle':
      return 'あめふらし'
    case 'speed-boost':
      return 'かそく'
    case 'battle-armor':
      return 'カブトアーマー'
    case 'sturdy':
      return 'がんじょう'
    case 'damp':
      return 'しめりけ'
    case 'limber':
      return 'じゅうなん'
    case 'sand-veil':
      return 'すながくれ'
    case 'static':
      return 'せいでんき'
    case 'volt-absorb':
      return 'ちくでん'
    case 'water-absorb':
      return 'みずのベール'
    case 'oblivious':
      return 'どんかん'
    case 'cloud-nine':
      return 'エアロック'
    case 'compound-eyes':
      return 'ふくがん'
    case 'insomnia':
      return 'ふみん'
    case 'color-change':
      return 'へんしょく'
    case 'immunity':
      return 'めんえき'
    case 'flash-fire':
      return 'もらいび'
    case 'shield-dust':
      return 'りんぷん'
    case 'own-tempo':
      return 'マイペース'
    case 'suction-cups':
      return 'きゅうばん'
    case 'intimidate':
      return 'いかく'
    case 'shadow-tag':
      return 'かげふみ'
    case 'rough-skin':
      return 'さめはだ'
    case 'wonder-guard':
      return 'ふしぎなまもり'
    case 'levitate':
      return 'ふゆう'
    case 'effect-spore':
      return 'ほうし'
    case 'synchronize':
      return 'シンクロ'
    case 'clear-body':
      return 'クリアボディ'
    case 'natural-cure':
      return 'しぜんかいふく'
    case 'lightning-rod':
      return 'ひらいしん'
    case 'serene-grace':
      return 'てんのめぐみ'
    case 'swift-swim':
      return 'すいすい'
    case 'chlorophyll':
      return 'ようりょくそ'
    case 'illuminate':
      return 'はっこう'
    case 'trace':
      return 'トレース'
    case 'huge-power':
      return 'ちからもち'
    case 'poison-point':
      return 'どくのトゲ'
    case 'inner-focus':
      return 'せいしんりょく'
    case 'magma-armor':
      return 'マグマのよろい'
    case 'water-veil':
      return 'みずのベール'
    case 'magnet-pull':
      return 'じりょく'
    case 'soundproof':
      return 'ぼうおん'
    case 'rain-dish':
      return 'あめうけざら'
    case 'sand-stream':
      return 'すなおこし'
    case 'pressure':
      return 'プレッシャー'
    case 'thick-fat':
      return 'あついしぼう'
    case 'early-bird':
      return 'はやおき'
    case 'flame-body':
      return 'ほのおのからだ'
    case 'run-away':
      return 'にげあし'
    case 'keen-eye':
      return 'するどいめ'
    case 'hyper-cutter':
      return 'かいりきバサミ'
    case 'pickup':
      return 'ものひろい'
    case 'truant':
      return 'なまけ'
    case 'hustle':
      return 'はりきり'
    case 'cute-charm':
      return 'メロメロボディ'
    case 'plus':
      return 'プラス'
    case 'minus':
      return 'マイナス'
    case 'forecast':
      return 'てんきや'
    case 'sticky-hold':
      return 'ねんちゃく'
    case 'shed-skin':
      return 'だっぴ'
    case 'guts':
      return 'こんじょう'
    case 'marvel-scale':
      return 'ふしぎなうろこ'
    case 'liquid-ooze':
      return 'ヘドロえき'
    case 'overgrow':
      return 'しんりょく'
    case 'blaze':
      return 'もうか'
    case 'torrent':
      return 'げきりゅう'
    case 'swarm':
      return 'むしのしらせ'
    case 'rock-head':
      return 'いしあたま'
    case 'drought':
      return 'ひでり'
    case 'arena-trap':
      return 'ありじごく'
    case 'vital-spirit':
      return 'やるき'
    case 'white-smoke':
      return 'しろいけむり'
    case 'pure-power':
      return 'ヨガパワー'
    case 'shell-armor':
      return 'シェルアーマー'
    case 'air-lock':
      return 'エアロック'
    case 'tangled-feet':
      return 'ちどりあし'
    case 'motor-drive':
      return 'でんきエンジン'
    case 'rivalry':
      return 'とうそうしん'
    case 'steadfast':
      return 'ふくつのこころ'
    case 'snow-cloak':
      return 'ゆきがくれ'
    case 'gluttony':
      return 'くいしんぼう'
    case 'anger-point':
      return 'いかりのつぼ'
    case 'unburden':
      return 'かるわざ'
    case 'heatproof':
      return 'たいねつ'
    case 'simple':
      return 'たんじゅん'
    case 'dry-skin':
      return 'かんそうはだ'
    case 'download':
      return 'ダウンロード'
    case 'iron-fist':
      return 'てつのこぶし'
    case 'poison-heal':
      return 'ポイズンヒール'
    case 'adaptability':
      return 'てきおうりょく'
    case 'skill-link':
      return 'スキルリンク'
    case 'hydration':
      return 'うるおいボディ'
    case 'solar-power':
      return 'サンパワー'
    case 'quick-feet':
      return 'はやあし'
    case 'normalize':
      return 'ノーマルスキン'
    case 'sniper':
      return 'スナイパー'
    case 'magic-guard':
      return 'マジックガード'
    case 'no-guard':
      return 'ノーガード'
    case 'stall':
      return 'あとだし'
    case 'technician':
      return 'テクニシャン'
    case 'leaf-guard':
      return 'リーフガード'
    case 'klutz':
      return 'ぶきよう'
    case 'mold-breaker':
      return 'かたやぶり'
    case 'super-luck':
      return 'きょううん'
    case 'aftermath':
      return 'ゆうばく'
    case 'anticipation':
      return 'きけんよち'
    case 'forewarn':
      return 'よちむ'
    case 'unaware':
      return 'てんねん'
    case 'tinted-lens':
      return 'いろめがね'
    case 'filter':
      return 'フィルター'
    case 'slow-start':
      return 'スロースタート'
    case 'scrappy':
      return 'きもったま'
    case 'storm-drain':
      return 'よびみず'
    case 'ice-body':
      return 'アイスボディ'
    case 'solid-rock':
      return 'ハードロック'
    case 'snow-warning':
      return 'ゆきふらし'
    case 'honey-gather':
      return 'みつあつめ'
    case 'frisk':
      return 'おみとおし'
    case 'reckless':
      return 'すてみ'
    case 'multitype':
      return 'マルチタイプ'
    case 'flower-gift':
      return 'フラワーギフト'
    case 'bad-dreams':
      return 'ナイトメア'
    case 'pickpocket':
      return 'わるいてぐせ'
    case 'sheer-force':
      return 'ちからずく'
    case 'contrary':
      return 'あまのじゃく'
    case 'unnerve':
      return 'きんちょうかん'
    case 'defiant':
      return 'まけんき'
    case 'defeatist':
      return 'よわき'
    case 'cursed-body':
      return 'のろわれボディ'
    case 'healer':
      return 'いやしのこころ'
    case 'friend-guard':
      return 'フレンドガード'
    case 'weak-armor':
      return 'くだけるよろい'
    case 'heavy-metal':
      return 'ヘヴィメタル'
    case 'light-metal':
      return 'ライトメタル'
    case 'multiscale':
      return 'マルチスケイル'
    case 'toxic-boost':
      return 'どくぼうそう'
    case 'flare-boost':
      return 'ねつぼうそう'
    case 'harvest':
      return 'しゅうかく'
    case 'telepathy':
      return 'テレパシー'
    case 'moody':
      return 'ムラっけ'
    case 'overcoat':
      return 'ぼうじん'
    case 'poison-touch':
      return 'どくしゅ'
    case 'regenerator':
      return 'さいせいりょく'
    case 'big-pecks':
      return 'はとむね'
    case 'sand-rush':
      return 'すなかき'
    case 'wonder-skin':
      return 'ミラクルスキン'
    case 'analytic':
      return 'アナライズ'
    case 'illusion':
      return 'イリュージョン'
    case 'imposter':
      return 'かわりもの'
    case 'infiltrator':
      return 'すりぬけ'
    case 'mummy':
      return 'ミイラ'
    case 'moxie':
      return 'じしんかじょう'
    case 'justified':
      return 'せいぎのこころ'
    case 'rattled':
      return 'びびり'
    case 'magic-bounce':
      return 'マジックミラー'
    case 'sap-sipper':
      return 'そうしょく'
    case 'prankster':
      return 'いたずらごころ'
    case 'sand-force':
      return 'すなのちから'
    case 'iron-barbs':
      return 'てつのトゲ'
    case 'zen-mode':
      return 'ダルマモード'
    case 'victory-star':
      return 'しょうりのほし'
    case 'turboblaze':
      return 'ターボブレイズ'
    case 'teravolt':
      return 'テラボルテージ'
    case 'aroma-veil':
      return 'アロマベール'
    case 'flower-veil':
      return 'フラワーベール'
    case 'cheek-pouch':
      return 'ほおぶくろ'
    case 'protean':
      return 'へんげんじざい'
    case 'fur-coat':
      return 'ファーコート'
    case 'magician':
      return 'マジシャン'
    case 'bulletproof':
      return 'ぼうだん'
    case 'competitive':
      return 'かちき'
    case 'strong-jaw':
      return 'がんじょうあご'
    case 'refrigerate':
      return 'フリーズスキン'
    case 'sweet-veil':
      return 'スイートベール'
    case 'stance-change':
      return 'バトルスイッチ'
    case 'gale-wings':
      return 'はやてのつばさ'
    case 'mega-launcher':
      return 'メガランチャー'
    case 'grass-pelt':
      return 'くさのけがわ'
    case 'symbiosis':
      return 'きょうせい'
    case 'tough-claws':
      return 'かたいツメ'
    case 'pixilate':
      return 'フェアリースキン'
    case 'gooey':
      return 'ぬめぬめ'
    case 'aerilate':
      return 'スカイスキン'
    case 'parental-bond':
      return 'おやこあい'
    case 'dark-aura':
      return 'ダークオーラ'
    case 'fairy-aura':
      return 'フェアリーオーラ'
    case 'aura-break':
      return 'オーラブレイク'
    case 'primordial-sea':
      return 'はじまりのうみ'
    case 'desolate-land':
      return 'おわりのだいち'
    case 'delta-stream':
      return 'デルタストリーム'
    case 'stamina':
      return 'じきゅうりょく'
    case 'wimp-out':
      return 'にげごし'
    case 'emergency-exit':
      return 'ききかいひ'
    case 'water-compaction':
      return 'みずがため'
    case 'merciless':
      return 'じょうおうのいげん'
    case 'shields-down':
      return 'リミットシールド'
    case 'stakeout':
      return 'はりこみ'
    case 'water-bubble':
      return 'すいほう'
    case 'steelworker':
      return 'はがねつかい'
    case 'berserk':
      return 'ぎゃくじょう'
    case 'slush-rush':
      return 'ゆきかき'
    case 'long-reach':
      return 'えんかく'
    case 'liquid-voice':
      return 'うるおいボイス'
    case 'triage':
      return 'ヒーリングシフト'
    case 'galvanize':
      return 'エレキスキン'
    case 'surge-surfer':
      return 'サーフテール'
    case 'schooling':
      return 'ぎょぐん'
    case 'disguise':
      return 'ばけのかわ'
    case 'battle-bond':
      return 'きずなへんげ'
    case 'power-construct':
      return 'スワームチェンジ'
    case 'corrosion':
      return 'ふしょく'
    case 'comatose':
      return 'ぜったいねむり'
    case 'queenly-majesty':
      return 'じょおうのいげん'
    case 'innards-out':
      return 'とびだすなかみ'
    case 'dancer':
      return 'おどりこ'
    case 'battery':
      return 'バッテリー'
    case 'fluffy':
      return 'もふもふ'
    case 'dazzling':
      return 'ビビッドボディ'
    case 'soul-heart':
      return 'ソウルハート'
    case 'tangling-hair':
      return 'カーリーヘアー'
    case 'receiver':
      return 'レシーバー'
    case 'power-of-alchemy':
      return 'かがくのちから'
    case 'beast-boost':
      return 'ビーストブースト'
    case 'rks-system':
      return 'ARシステム'
    case 'electric-surge':
      return 'エレキメイカー'
    case 'psychic-surge':
      return 'サイコメイカー'
    case 'misty-surge':
      return 'ミストメイカー'
    case 'grassy-surge':
      return 'グラスメイカー'
    case 'full-metal-body':
      return 'メタルプロテクト'
    case 'shadow-shield':
      return 'シャドーシールド'
    case 'prism-armor':
      return 'プリズムアーマー'
    case 'neuroforce':
      return 'ブレインフォース'
    case 'intrepid-sword':
      return 'ふとうのけん'
    case 'dauntless-shield':
      return 'ふくつのたて'
    case 'libero':
      return 'リベロ'
    case 'ball-fetch':
      return 'ボールぐるい'
    case 'cotton-down':
      return 'わたげ'
    case 'propeller-tail':
      return 'スクリューおびれ'
    case 'mirror-armor':
      return 'ミラーアーマー'
    case 'gulp-missile':
      return 'うのミサイル'
    case 'stalwart':
      return 'すじがねいり'
    case 'steam-engine':
      return 'じょうききかん'
    case 'punk-rock':
      return 'パンクロック'
    case 'sand-spit':
      return 'すなはき'
    case 'ice-scales':
      return 'こおりのりんぷん'
    case 'ripen':
      return 'じゅくせい'
    case 'ice-face':
      return 'アイスフェイス'
    case 'power-spot':
      return 'パワースポット'
    case 'mimicry':
      return 'へんげんじざい'
    case 'screen-cleaner':
      return 'バリアフリー'
    case 'steely-spirit':
      return 'はがねのせいしん'
    case 'perish-body':
      return 'ほろびのボディ'
    case 'wandering-spirit':
      return 'さまようたましい'
    case 'gorilla-tactics':
      return 'ごりむちゅう'
    case 'neutralizing-gas':
      return 'かがくへんかガス'
    case 'pastel-veil':
      return 'パステルベール'
    case 'hunger-switch':
      return 'はらぺこスイッチ'
    case 'quick-draw':
      return 'クイックドロウ'
    case 'unseen-fist':
      return 'みえざるこぶし'
    case 'curious-medicine':
      return 'きみょうなくすり'
    case 'transistor':
      return 'トランジスタ'
    case 'dragons-maw':
      return 'りゅうのあぎと'
    case 'chilling-neigh':
      return 'しろのいななき'
    case 'grim-neigh':
      return 'くろのいななき'
    case 'as-one-glastrier':
      return 'はくばじょうおう'
    case 'as-one-spectrier':
      return 'くろばじょうおう'
    case 'lingering-aroma':
      return 'とれないにおい'
    case 'seed-sower':
      return 'こぼれダネ'
    case 'thermal-exchange':
      return 'ねつこうかん'
    case 'anger-shell':
      return 'いかりのこうら'
    case 'purifying-salt':
      return 'きよめのしお'
    case 'well-baked-body':
      return 'こんがりボディ'
    case 'wind-rider':
      return 'かぜのり'
    case 'guard-dog':
      return 'ばんけん'
    case 'rocky-payload':
      return 'いわはこび'
    case 'wind-power':
      return 'ふうりょくでんき'
    case 'zero-to-hero':
      return 'マイティチェンジ'
    case 'commander':
      return 'しれいとう'
    case 'electromorphosis':
      return 'でんきにかえる'
    case 'protosynthesis':
      return 'こだいかっせい'
    case 'quark-drive':
      return 'クォークチャージ'
    case 'good-as-gold':
      return 'おうごんのからだ'
    case 'vessel-of-ruin':
      return 'わざわいのうつわ'
    case 'sword-of-ruin':
      return 'わざわいのつるぎ'
    case 'tablets-of-ruin':
      return 'わざわいのおふだ'
    case 'beads-of-ruin':
      return 'わざわいのたま'
    case 'orichalcum-pulse':
      return 'ひひいろのこどう'
    case 'hadron-engine':
      return 'ハドロンエンジン'
    case 'opportunist':
      return 'びんじょう'
    case 'cud-chew':
      return 'はんすう'
    case 'sharpness':
      return 'きれあじ'
    case 'supreme-overlord':
      return 'そうだいしょう'
    case 'costar':
      return 'きょうえん'
    case 'toxic-debris':
      return 'どくげしょう'
    case 'armor-tail':
      return 'テイルアーマー'
    case 'earth-eater':
      return 'どしょく'
    case 'mycelium-might':
      return 'きんしのちから'
    case 'minds-eye':
      return 'しんがん'
    case 'supersweet-syrup':
      return 'かんろなミツ'
    case 'hospitality':
      return 'おもてなし'
    case 'toxic-chain':
      return 'どくのくさり'
    case 'embody-aspect':
      return 'おもかげやどし'
    case 'tera-shift':
      return 'テラスチェンジ'
    case 'tera-shell':
      return 'テラスシェル'
    case 'teraform-zero':
      return 'ゼロフォーミング'
    case 'poison-puppeteer':
      return 'どくくぐつ'
    case 'mountaineer':
      return 'やまのぼり'
    case 'wave-rider':
      return 'なみのり'
    case 'skater':
      return 'スケーター'
    case 'thrust':
      return 'つきさし'
    case 'perception':
      return 'かんち'
    case 'parry':
      return 'うけながし'
    case 'instinct':
      return 'ほんのう'
    case 'dodge':
      return 'かわす'
    case 'jagged-edge':
      return 'ギザギザエッジ'
    case 'frostbite':
      return 'しもやけ'
    case 'tenacity':
      return 'しぶとさ'
    case 'pride':
      return 'プライド'
    case 'deep-sleep':
      return 'ぐっすり'
    case 'power-nap':
      return 'パワーナップ'
    case 'spirit':
      return 'スピリット'
    case 'warm-blanket':
      return 'あったかいもうふ'
    case 'gulp':
      return 'ごくごく'
    case 'herbivore':
      return 'そうしょくしゅ'
    case 'sandpit':
      return 'すなあな'
    case 'hot-blooded':
      return 'あつけつ'
    case 'medic':
      return 'メディック'
    case 'life-force':
      return 'せいめいりょく'
    case 'lunchbox':
      return 'おべんとう'
    case 'nurse':
      return 'かんごふ'
    case 'melee':
      return 'せんとう'
    case 'sponge':
      return 'スポンジ'
    case 'bodyguard':
      return 'ボディーガード'
    case 'hero':
      return 'ヒーロー'
    case 'last-bastion':
      return 'さいごのとりで'
    case 'stealth':
      return 'ステルス'
    case 'vanguard':
      return 'ぜんえい'
    case 'nomad':
      return 'ほうろうしゃ'
    case 'sequence':
      return 'れんさ'
    case 'grass-cloak':
      return 'くさのミノ'
    case 'celebrate':
      return 'おいわい'
    case 'lullaby':
      return 'こもりうた'
    case 'calming':
      return 'なだめる'
    case 'daze':
      return 'めまい'
    case 'frighten':
      return 'おびえる'
    case 'interference':
      return 'じゃま'
    case 'mood-maker':
      return 'ムードメーカー'
    case 'confidence':
      return 'じしん'
    case 'fortune':
      return 'こううん'
    case 'bonanza':
      return 'だいせいこう'
    case 'explode':
      return 'ばくはつ'
    case 'omnipotent':
      return 'ぜんのうしゃ'
    case 'share':
      return 'わかちあい'
    case 'black-hole':
      return 'ブラックホール'
    case 'shadow-dash':
      return 'かげぎえ'
    case 'sprint':
      return 'ダッシュ'
    case 'disgust':
      return 'いやがる'
    case 'high-rise':
      return 'たかとび'
    case 'climber':
      return 'クライマー'
    case 'flame-boost':
      return 'ほのおブースト'
    case 'aqua-boost':
      return 'みずブースト'
    case 'run-up':
      return 'かけあし'
    case 'conqueror':
      return 'せいふくしゃ'
    case 'shackle':
      return 'しばり'
    case 'decoy':
      return 'おとり'
    case 'shield':
      return 'シールド'
    default:
      return 'ふめい'
  }
}
